import type { Metadata } from 'next'
import { Inter, Libre_Baskerville } from 'next/font/google'
import './globals.css'
import Footer from '@/components/shared/Footer';


const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
});
const libreBaskerville = Libre_Baskerville({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: '--font-libre-baskerville',
  display: "swap",
});


export const metadata: Metadata = {
  title: 'Slum2Stage',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${libreBaskerville.variable} ${inter.variable}`}>
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  )
}
